project_name: myBacktest
resources_dir: resources
output_dir: outputs_lol
prompt_lib: prompt_library_default.csv
coding_temp: 0.3
strategy_descr_temp: 0.3
strategy_feedback_temp: 0.3
vis_strat_temp: 0.3
